FileNotFoundError
Traceback (most recent call last):
  File "E:\Github\PhoVSR\template\evaluator.py", line 104, in __call__
    self.show(dataloader)
  File "E:\Github\PhoVSR\template\evaluator.py", line 115, in show
    for raw_data,val_data in dataloader:
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Github\PhoVSR\datas\__init__.py", line 191, in __getitem__
    line=open(self.text_pth+file+".txt","r",encoding="utf-8").readline().strip()
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Github\\PhoVSR\\datas/info/CMLR/texts/s8#20160206_section_3_075.66_077.89.txt'



FileNotFoundError
Traceback (most recent call last):
  File "E:\Github\PhoVSR\template\evaluator.py", line 104, in __call__
    self.show(dataloader)
  File "E:\Github\PhoVSR\template\evaluator.py", line 115, in show
    for raw_data,val_data in dataloader:
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Github\PhoVSR\datas\__init__.py", line 191, in __getitem__
    line=open(self.text_pth+file+".txt","r",encoding="utf-8").readline().strip()
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\Github\\PhoVSR\\datas/info/CMLR/texts/.txt'



